branch-defaults:
  default:
    environment: $ENVIRONMENT
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: $APP_NAME
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: $AWS_REGION
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
